In [1]:
import numpy as np

In [2]:
our_list = [1,2,3]
our_list

[1, 2, 3]

In [3]:
np.array(our_list)

array([1, 2, 3])

In [4]:
our_matrix = [[1,2,3],[4,5,6],[7,8,9]]
our_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(our_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# NumPy Indexing

In [7]:
import numpy as np

In [8]:
#reating sample array
arr = np.arange(0,11)

In [9]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Bracket Indexing

In [10]:
#get a value at an index
arr[8]

8

In [11]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [12]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

# Broadcasting

In [13]:
#Setting a value with index range (Braodcasting)

arr[0:5]= 105

#Show
arr

array([105, 105, 105, 105, 105,   5,   6,   7,   8,   9,  10])

In [14]:
#reset array, we'll see why I had to reset in a moment
arr = np.arange(0,11)
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
#important notes on Slices

slice_of_arr[:]=100
#Show slice
slice_of_arr

array([100, 100, 100, 100, 100, 100])

Now note the changes also occur in our original array!

In [17]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [18]:
arr_copy = arr.copy()

In [19]:
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

# Indexing a 2D array(,atrices)

In [21]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
#indexing row
arr_2d[1]

array([20, 25, 30])

In [23]:
#Format is arr_2d[row][col] or arr_2d[row,col]

#Getting individual element value
arr_2d[1][1]

25

In [24]:
#Getting individual element value
arr_2d[1][1]

25

In [26]:
#2D array slicing

#Shape(2,2) from top right coner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [27]:
#Shape bottom row

arr_2d[2,:]

array([35, 40, 45])

# Data Processing

# Built-in Methods

In [28]:
import numpy as np

# arange

In [29]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0,10,4)

array([0, 4, 8])

# zeros and ones

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [32]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# linspace

In [36]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

# eye

In [37]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Random

## rand

In [38]:
np.random.rand(2)

array([0.62263016, 0.40809004])

In [39]:
np.random.rand(5,4)

array([[0.19736296, 0.09454865, 0.45952867, 0.42114039],
       [0.21291462, 0.16481003, 0.86339199, 0.31184232],
       [0.47521655, 0.33147153, 0.44048254, 0.19543027],
       [0.5273578 , 0.21206192, 0.09938866, 0.82739495],
       [0.73003156, 0.76186485, 0.72325876, 0.39539513]])

## randn

In [40]:
np.random.randn(2)

array([1.49016978, 0.25441387])

In [41]:
np.random.randn(5,4)

array([[-0.24956337,  0.36149747, -0.18453829, -0.83115015],
       [ 2.16596207, -0.37397849,  1.85737108, -0.98860306],
       [ 0.88120814, -0.83883633, -1.49664321,  0.90020619],
       [-0.32348896, -0.19757818, -0.61542687,  2.38320307],
       [ 0.88644798, -0.85885123, -0.71345849,  1.65213268]])

## randint

In [42]:
np.random.randint(2)

0

In [43]:
np.random.randint(1,100,10)

array([56, 91,  4, 38, 97, 47, 86, 13, 97, 98])

## Array Attributes and Methods

In [44]:
arr = np.arange(1,37)
ranarr = np.random.randint(0,50,10)

In [45]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [46]:
ranarr

array([13, 42, 24, 46, 12, 21,  0, 28, 30, 32])

# Reshape

In [47]:
arr.reshape(6,6).shape

(6, 6)

# max,min,argmax,argmin

In [48]:
ranarr

array([13, 42, 24, 46, 12, 21,  0, 28, 30, 32])

In [49]:
ranarr.max()

46

In [50]:
ranarr.argmax()

3

In [51]:
ranarr.min()

0

In [52]:
ranarr.argmin()

6

# Mathematical Functions

## Universal Array Functions

In [53]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [55]:
#Calculating exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [56]:
#same as arr.max()

In [57]:
np.max(arr)

10

In [59]:
np.log(arr)

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])